# Generated by Django 4.1.3 on 2023-03-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('comment', models.TextField()),
                ('is_active', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
