# Generated by Django 4.1.3 on 2023-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
