# Generated by Django 3.2.18 on 2023-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
