# Generated by Django 4.1.3 on 2023-04-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_id', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
