# Generated by Django 3.2.18 on 2023-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
